### ISSUE TITLE
Create npm module

### ISSUE THREAD

**Issue by unsuitable001** [unsuitable001/memoryJS#1]
Create npm module out of this library & submit a PR.

**Comment by Sjain020188** [comment]
I'd like to try this.

**Comment by dolani** [comment]
I will like to take a stab on this.

**Comment by unsuitable001** [comment]
@dolani I think someone is already working on it. You can still proceed with your work if you have better solution (if possible). The most suitable solution will get merged.
:smile: 
You can put a :star2: & share & fork.
I appreciate your efforts a lot.
