### ISSUE TITLE
[unit testing] Add coverage check using codecov

### ISSUE THREAD

**Issue by unsuitable001** [unsuitable001/memoryJS#4]
[unit testing] Add coverage check using CODEBEAT.
You have to write the tests & try to fix if any error occurs.
Refer - https://hub.codebeat.co/docs/test-coverage-reports#section-setting-up-for-javascript-typescript

coverage will only be calculated if previous tests are passed & it's in the master branch.

**Comment by theashraf** [comment]
Can i take this one ?

**Comment by unsuitable001** [comment]
Sure. Go ahead. Best of luck.
